### PR TITLE
Create SanketKN_missing_number.py

### PR DESCRIPTION
**Pull request by SanketKN**
accept it broooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

### CODE REVIEW

**Comment by pawank0411** [comment]
Please edit your comment. This is not any social media page.

**Comment by SanketKN** [comment]
Done. Sorry bhaiya

**Comment by pawank0411** [comment]
You can make a new PR

**Comment by SanketKN** [comment]
Thank you Bhaiya. I'm unable to do it currently as I don't have the laptop
with me so I'll surely do it tomorrow morning.

**Pull request closed without merging**
