### PR TITLE
bit string solved..4th qn

### PR DESCRIPTION
**Pull request by ash0202**

### CODE REVIEW

**Comment by KejariwalAyush** [comment]
change folder name to GitHub id and file name to githubid_ques.java

**Comment by ash0202** [comment]
done..

**Comment by pawank0411** [comment]
> 
> 
> done.
@ash0202 you need to also change the folder name to your GitHub id

**Comment by ash0202** [comment]
sorry.. i am not getting which floder you are talking about..can u plz explian which one to rename

**Comment by KejariwalAyush** [comment]
The folder which is named as yourName

Replace it with your githubidname

**Comment by ash0202** [comment]
yes done..thank you

**Pull request merged**
