### PR TITLE
Coin Piles

### PR DESCRIPTION
**Pull request by rahulkumarjha21**

### CODE REVIEW

**Comment by KejariwalAyush** [comment]
Why your all files have 2 extension (.java. java)

**Comment by rahulkumarjha21** [comment]
Do I need to delete this and create a new pr or will this be accepted afterward I will not use 2 extensions

**Comment by rahulkumarjha21** [comment]
Renamed the file

**Comment by KejariwalAyush** [comment]
Rename all the files

**Comment by rahulkumarjha21** [comment]
Renamed all the files

**Pull request merged**
