### PR TITLE
Utkarsh's initial commit

### PR DESCRIPTION
**Pull request by UtkarshShankar**
Consider an algorithm that takes as input a positive integer n. If n is even, the algorithm divides it by two, and if n is odd, the algorithm multiplies it by three and adds one. The algorithm repeats this, until n is one. For example, the sequence for n=3 is as follows:
3→10→5→16→8→4→2→1

Print a line that contains all values of n during the algorithm.

### CODE REVIEW

**Comment by KejariwalAyush** [comment]
Add the question as Comments on top

**Comment by UtkarshShankar** [comment]
You are given all numbers between 1,2,…,n except one. Your task is to find the missing number.

**Comment by KejariwalAyush** [comment]
Bro, you have to add the question in the program as comments not here.
Also, you can remove 2nd file and make a pr for that after this one gets approved

**Comment by UtkarshShankar** [comment]
i have removed the 2nd file and modified the 1st  file

**Pull request merged**
